---
title: "Final Project: State/Region Incarceration Levels by Sex"
author: "Ava, Alex, Luci, and Christine"
date: "6-7-26"
output: html_document
---

## Conclusion

### Project Importance

Overall, our project looked at 1) state incarceration rates—including combining the states into regions—deviating from the trend of only measuring federal incarceration rates, 2) observed incarceration rates by sex in each state/region, and 3) evaluated each state’s policies on prostitution laws to see whether the strictness of states’ prostitution laws could be correlated to disproportionately high incarceration rates among females compared to males. The importance of this project relies on how incarceration numbers can drastically vary from state to state/region to region, which is hidden when observing federal rates that cumulate state incarceration numbers together. 

This project looks at the total number of people incarcerated in each state, the total number of people incarcerated per 100,000 people in each state’s population, and the number of females/males incarcerated in each state/region per 100,000 people. On a regional level, this project looks at the total number of people incarcerated in each region, the number of people incarcerated per 100,000 in population for each region, the number of females incarcerated per 100,000 in population in each region, the number of females incarcerated per 100,000 in population in each region, and the number of males incarcerated per 100,000 in population in each region. Moreover, we also included spatial graphs. The spatial graphs look at the number of females incarcerated per 100,000 people in each state and another spatial graph observes how the number of females incarcerated per 100,000 people to the number of males incarcerated per 100,000 people. By observing the incarceration numbers for every 100,000 people and total incarceration numbers, these data visualizations help us better understand state and regional-level incarceration numbers and how states/regions differ by sex in incarcerating people. 

This project also takes into consideration how sex can be a social stratifier within state/region incarceration rates, especially given that women are being incarcerated at higher rates over the past several decades (Sentencing Project 2025). This project finds that western states (e.g., Idaho, Montana, Wyoming) and southern states (e.g. Texas, Florida) have disproportionately high total incarceration numbers and number of females incarcerated per 100,000 people in the state. This may indicate that southern and western states may have a more punitive approach to policies that influence their incarceration numbers. We encourage more research to be done in this space and to further interrogate why states/the South and West region appear to have higher incarceration numbers compared to the rest of the country. 

### Results 

### *Incarceration Numbers Per 100,000 and Total Incarceration Numbers*

When we looked at total people incarcerated per state, Texas had the highest number of people incarcerated, California second, Florida third, and Georgia 4th. Out of the top 4 states with the highest number of incarceration, three of the states (Texas, Georgia, and Florida) are from the South. On the other hand, the states with the lowest number of incarcerated people were Vermont, Rhode Island, Alaska, and Maine. Out of the top 4 states with lowest numbers of incarcerated people, three of the states are from the Northeast (Vermont, Maine, and Rhode Island). 

However, it is important to consider how population size plays a critical role in this—the larger the state population, the more people who may be incarcerated, even if the incarceration rate is actually lower compared to a smaller population-sized state. Thus, when measuring the number of incarcerated people in each state per 100,000 people, the top 4 states change, which may be surprising. Mississippi has the higher number of people incarcerated per 100,000 people in the state, Louisiana second, Arkansas third, and Oklahoma fourth. All of these four states are from the South. When looking at the four states with the lowest number of people incarcerated per 100,000 people, Massachusetts has the lowest, Maine the second lowest, Rhode Island the third lowest, and Vermont the fourth lowest. All of these states are from the Northeast. 

This data analysis points to how the South has more incarcerated people than other regions, while the Northeast region has less incarcerated people than other regions. It may be surprising that states’ level of incarceration changes when population size is taken into consideration. Yet, even though the specific states with the highest/lowest incarceration numbers may change when viewing the flat total incarcerated vs. total incarcerated per 100,000 people in the population, the states’ regions stay quite similar. Accordingly, when we measured the region incarceration numbers, the South had the highest incarceration numbers when viewing the data results by 100,000 people in each region and total incarceration numbers per region. The Northeast also remained about the lowest in incarceration measures in both results as well. There may be certain policies and normalized behaviors from law enforcement in the South that lead to these disproportionately high incarceration numbers compared to other regions/states. 

Next, when looking at how incarceration by sex may differ by state, Idaho, Montana, South Dakota, and Oklahoma were some states that incarcerated the most females per 100,000 people in each state. There is variance in regions: Idaho and Montana are from the West, South Dakota from the Midwest, and Oklahoma is from the South. Massachusetts, New Jersey, Vermont, and New York were some states that incarcerated the least females per 100,00 people in each state. All four states are from the Northeast. The regional data also shows that the South has the most females incarcerated when looking at every 100,000 people and by total population across regions, and the Northeast has the lowest number of females incarcerated when looking at both incarceration numbers for every 100,000 people and by total population across regions (when not accounting for Hawaii and Alaska because as mentioned earlier, those two states do not belong to regions). Once again, the South has disproportionately high numbers of females incarcerated. 

To combine data analysis and policy relevance, this project outlines each state’s prostitution laws since females have disproportionately higher rates of arrest on prostitution charges than males. We highlight this policy to identify whether it may be correlated to sex discrimination in incarceration. Through the use of a t-test, this project identifies that stricter prostitution laws are statistically insignificant in explaining the heightened incarceration rates of females. When looking at states with the strictest prostitution laws (including Texas, South Carolina, Oklahoma, and more), they did not all have disproportionately higher incarceration numbers of females per 100,000 people. Although prostitution laws disproportionately affect females in regards to their criminal legal system contact, this does not necessarily lead to higher incarceration numbers among females. This means that there may be other laws, policies, as well as police bias, that can lead to unequal criminal legal system contact among females in different states.  

### Next Steps and Future Directions

We conclude by stating that more research needs to be done to understand how policies shape incarceration numbers. This project points to why there should be a sustained focus on looking at state and regional differences within incarceration rates. The U.S. is considered to have exceptionally high incarceration rates, but the data shows that Southern states are incarcerating people at much higher rates than the Northeast when looking at both total incarceration numbers per region and incarceration numbers per 100,000 people in the region. Generalizing U.S. incarceration rates under a national total can guise how some states are disproportionately contributing to the total incarceration numbers. If we are to reduce total incarceration numbers, this project highlights what states may need to focus on reform the most (i.e., the states with the highest incarceration numbers). 

This project contributes to understandings that emphasize how local states/regions are contributing disproportionately to the high incarceration rates in the country, pointing to the importance of further evaluating local and state policies (Vera Institute of Justice 2026). The South is also incarcerating females at a disproportionately high rate compared to other regions. Future research can seek to more closely understand why—what is public opinion in the South towards criminal legal system punishment? How might political ideology (conservative vs. liberal ideals) shape opinions and policies within these states? How are law enforcement officers being trained in the South compared to the Northeast in ways that might lead to higher arrests and incarceration? All of these are future directions and next steps that this project can go in to better understand regional/state differences in national incarceration numbers. 

Although stricter prostitution laws (which are laws that disproportionately apply to the female sex) were found to be statistically insignificant in explaining the differences in the numbers of females incarcerated in states, this does not mean that prostitution laws have no significance on individuals' lived experiences. Thus, we encourage qualitative research that employs interviews and ethnographic fieldnotes to understand how strict prostitution laws are shaping peoples’ lives. Moreover, there may be other mechanisms that we did not explore in this project that can explain the disproportionately high female incarceration numbers in the South. Is there higher policing in some states? How much discretion do court officials have in such laws being applied? All of these questions are directions that this research can go in to help better understand female incarceration numbers. 

## Table of Contents

* <a href="index.html">Index</a>
* <a href="Introduction.html">Introduction</a>
* <a href="DataSources.html">Data Sources</a> 
* <a href="DataProcessingandMethods.html">Data Processing and Methods</a>
* <a href="Limitations.html">Limitations</a> 
* <a href="Conclusion.html">Conclusion</a> 
* <a href="ContributionsReferencesAppendix.html">Contributions, References, and Appendix</a> 
* <a href="CompleteReport.html">Complete Report</a> 