---
title: "Final Project: State/Region Incarceration Levels by Sex"
author: "Ava, Alex, Luci, and Christine"
date: "6-7-26"
output: html_document
---

# Final Project Proposal

## Introduction 

The United States of America is the world's leader in incarceration, jailing and imprisoning almost two million people at this very moment. Incarceration rates skyrocketed in the 1970s as a response to politically imposed fear surrounding the “war on drugs” and a racialized crackdown on crime, allowing incarceration to reach its peak in 2009 (e.g., Alexander 2010). These trends of heightened jailing are often referred to as mass incarceration, where “the U.S. incarcerates more people than any nation in the world” (Cullen 2018).  This is a phenomenon that is often racialized and classed, targeting those on the margins and disproportionately affecting poor Black people (e.g., Clair 2020). 

While incarceration rates began to decline in 2010 and dropped sharply during the COVID-19 pandemic, recent years starting in 2022 have seen them trend upward again (Nellis and Pearce 2026). This is especially alarming given that the Vera Institute of Justice found that “there is a very weak relationship between higher incarceration rates and lower crime rates”(Stemen 2017). As a result of this heightened incarceration, more individuals became exposed to consequences beyond loss of freedom, which include potential violence behind bars, forced gang involvement, exposure to disease, and the potential for death while in custody. Additionally, punishment does not end just with the time spent incarcerated, as it often leads to further barriers after imprisonment, including legal, social, financial, and psychological obstacles, coupled with potential discrimination when it comes to securing employment and housing. The effects of incarceration do not apply simply to those incarcerated but also hold additional collateral consequences for the families and loved ones of those incarcerated (e.g., Megan 2019).

Recognizing the harmful impacts of incarceration and the steady increases in national incarceration rates in the past few years, our group hopes to discover whether high levels of prison incarceration are primarily concentrated in a few states and/or regions — which contribute disproportionately to the national average — or if all states and regions are facing high and increasing rates of incarceration within prisons. Some language surrounding mass incarceration has previously referred to the United States as a mass contributor without recognizing if specific states contribute less or higher to this large-scale issue (e.g., Sawyer, Nam-Sonenstein, Wagner 2026) . Additionally, while some organizations (e.g., Nellis and Pearce 2026) do make efforts to spotlight states with heightened incarceration rates, regional differences are not often mentioned online. While we were initially planning to compare state-level incarceration rates to federal incarceration rates, we ultimately decided, based on the data available, that it would be more informative to conduct analyses within the state-level/regional context to keep the focus on these areas. Studying regions alongside individual states helps us to understand whether states in proximity to each other have similar patterns in regards to incarceration. Overall, this allows us to understand and answer one of our central research questions: How do incarceration levels vary from state to state and region by region? 

Another variable of interest is whether the number of females and males incarcerated differs across states, as well as if this is correlated to policies that target a specific sex. Historically, the literature surrounding incarceration often centers males without elevating policies or actions that may leave females most vulnerable to incarceration. Retired Sociology Professor Sandra Enos even asserts in her piece, "Mass Incarceration: Triple Jeopardy for Women in a 'Color-Blind' and Gender-Neutral Justice System," that the "strain of research [regarding the war on crime] has focused on men" (2012).Therefore, our work aims to bridge this gap and focus on whether sex can be a stratifier within incarceration numbers. In this project, we conflated gender and sex, given that our dataset only provided data based on sex.

While there are far more men facing the criminal system than women, the Council on Criminal Justice reveals that “the incarceration rate for women in U.S. prisons and jails has trended upward over the past several decades” (Yen 2024), indicating that sex discrimination may play a role in heightened incarceration. Therefore, this leads to our secondary research question: How do state-level prison incarceration numbers vary by sex? Posing this research question will allow us to understand if sex is a characteristic leading to disproportionate rates of incarceration across states.

By leveraging ready-made data from the Bureau of Justice Statistics and the U.S. Census, we identified states’ incarceration numbers, including by sex, and also controlled for population size. Therefore, it may indicate which states should make greater efforts toward reform. In addition to better understanding if sex played a factor in incarceration rate disproportionalities, we investigated states with harsher punishment for a crime often associated with female offenders: prostitution. FBI Data on offenses charged in 2017 reveals that nearly every crime, from robbery to gambling, had more than a majority of arrests and charges placed on men. Yet, the one exception is "prostitution and commercialized vice," a crime that resulted in 61% of those arrests coming from female offenders (Federal Bureau of Investigation 2017). While prostitution is legalized in certain parts of Nevada, all other states criminalize sex work (Decriminalize Sex Work 2023). While most states classify prostitution as a misdemeanor, 12 states, which we classify as "stricter states," have harsher punishments for this crime. Texas, Utah, Pennsylvania, Nevada, Kentucky, West Virginia, Vermont, Oklahoma, Louisiana, Idaho, Indiana, and Illinois will turn prostitution offenses into a felony charge or meet this crime with felony level punishments, such as 3 years' imprisonment under certain circumstances (repeat offenses or doing sex work while knowingly having Human Immunodeficiency Virus (HIV)) (Decriminalize Sex Work 2023). By focusing on states with stricter prostitution policies, this may reveal whether states with stricter punishments for crimes applied more frequently to females are correlated with higher female incarceration rates. Additionally, a 2020 study performed by health researchers Kim and Peterson indicated that despite only a small proportion of those incarcerated in female institutions being detained due to prostitution related offenses, roughly half of those incarcerated in their study had engaged in sex work despite not being incarcerated for sex work. Overall, this indicating that criminalizing sex work has the potential to inadvertently criminalize those already living on the margins, in addition to potentially influencing state-level incarceration numbers based on the sex of the offender. This is why we chose to focus on this topic for our project. 

The results and findings of our research will be further explored in the following sections, using computational social science methods in R, including data visualization and t-tests, comparing incarceration levels across different states.

## Table of Contents

* <a href="index.html">Index</a>
* <a href="Introduction.html">Introduction</a>
* <a href="DataSources.html">Data Sources</a> 
* <a href="DataProcessingandMethods.html">Data Processing and Methods</a>
* <a href="Limitations.html">Limitations</a> 
* <a href="Conclusion.html">Conclusion</a> 
* <a href="ContributionsReferencesAppendix.html">Contributions, References, and Appendix</a> 
* <a href="CompleteReport.html">Complete Report</a> 

